### ISSUE TITLE
PSRP Copy/Fetch

### ISSUE THREAD

**Issue by nbulischeck** [jborean93/pypsrp#43]
Would it be possible to implement a PSRP version of Copy and Fetch?

I've authed to the server and can run commands with `execute_ps`, but copy and fetch are out of bounds because they use WinRS instead of PSRP. WinRS copy/fetch yields `(Code: 5, Machine: 10.10.10.1, Reason: Access is denied.)`.

Would this be difficult because the current implementation uses `Process`?

https://github.com/jborean93/pypsrp/blob/aab984de61430312232e1a621060c84397b26712/pypsrp/client.py#L155-L164

**Comment by jborean93** [comment]
Fetch already uses PSRP to read the file bytes https://github.com/jborean93/pypsrp/blob/master/pypsrp/client.py#L297. The copy side can technically be done but I kept it with the raw WinRS side as that's the fastest way possible to copy a file across. I could look again but have never found a satisfactory solution.

**Comment by nbulischeck** [comment]
Glad to hear that Fetch uses PSRP! I don't doubt that WinRS would be very fast - it definitely looks it. Perhaps an alternate method like `copy_psrp` or a flag as opposed to a replacement of the already good WinRS implementation.

For reference, to copy files WinRM-FS does this:

https://github.com/WinRb/winrm-fs/blob/2ecb6e8fa1ceaecd68d2b1ce46f834a09267e189/lib/winrm-fs/core/file_transporter.rb#L448-L494

Something I implemented (which wasn't great imo) going off of that WinRM-FS code was:

https://github.com/nbulischeck/PyShellRM/blob/e26662861de999bb9b5d3db7b95c49e7080c9765/shell.py#L115-L127

https://github.com/nbulischeck/PyShellRM/blob/e26662861de999bb9b5d3db7b95c49e7080c9765/shell.py#L20-33

**Comment by jborean93** [comment]
The biggest issue I've come across with copy is when the file being copied is quite large and exceeds the memory limits of the pipeline input size imposed on the PSRP endpoint. https://github.com/WinRb/winrm-fs/blob/2ecb6e8fa1ceaecd68d2b1ce46f834a09267e189/lib/winrm-fs/core/file_transporter.rb#L471 might be a way of bypassing that (I doubt it though) but still doesn't hurt to try.

**Comment by nbulischeck** [comment]
Are you going to give this a go? Or should I start on it and you can accept/deny the PR

**Comment by jborean93** [comment]
You are more than welcome to try it out. If you can get large files working without a large overhead I would be willing to replace the default copy implementation. I don't have much time on my hands right now unfortunately so it would be a while before I can give a closer look at it.

**Comment by jborean93** [comment]
I had a play around with this a bit more and unfortunately couldn't find anything satisfactory. The ScriptBlock cache clearing does not help in this case. The problem is based on when the server starts up the remote runspace and set's the max received data size based on the configuration `MaximumReceivedDataSizePerCommandMB` that is set during registration. I created a 1GB file and modified the code to use the PSRP runspace and send the input under a PowerShell pipeline and it fails with

```
Traceback (most recent call last):
  File "/Users/jborean/dev/pypsrp/copy_file.py", line 17, in <module>
    print(c.copy(src_path, dest_path))
  File "/Users/jborean/dev/pypsrp/pypsrp/client.py", line 158, in copy
    powershell.invoke(input=read_gen)
  File "/Users/jborean/dev/pypsrp/pypsrp/powershell.py", line 1093, in invoke
    redirect_shell_error_to_out, remote_stream_options)
  File "/Users/jborean/dev/pypsrp/pypsrp/powershell.py", line 1060, in begin_invoke
    command_id=self._command_id)
  File "/Users/jborean/dev/pypsrp/pypsrp/shell.py", line 294, in send
    selector_set=self._selector_set)
  File "/Users/jborean/dev/pypsrp/pypsrp/wsman.py", line 313, in send
    option_set, selector_set, timeout)
  File "/Users/jborean/dev/pypsrp/pypsrp/wsman.py", line 382, in invoke
    raise self._parse_wsman_fault(err.response_text)
pypsrp.exceptions.WSManFaultError: Received a WSManFault message. (Code: 2152992672, Machine: server2016.domain.local, Provider: microsoft.powershell, Provider Path: C:\Windows\system32\pwrshplugin.dll, Provider Fault: The total data received from the remote client exceeded the allowed maximum. The allowed maximum is 52428800.)
```

I can't see a way that would be able to adjust this value at runtime, even if there was it would be a bit of a security flaw. This unfortunately means that I would not be able to efficiently transfer a large file using pure PSRP without resorting to separate commands which is an added message to the whole payload.

I did take that step further and found it slowed down quite dramatically to go this route, maybe there are some efficiencies to be gained but the current operation takes 2m for a 1GB file compared to 20+ minutes for a command per chunk.

**Comment by jborean93** [comment]
Happy to still include it but would prefer to only enable it under a separate kwarg that is set to `False` by default.

**Comment by jborean93** [comment]
This was bugging me a too much and I found a "hack" I think I might be happy with going forward that disables the max received size check. It works for most of the PowerShell versions I've tested with so far but there's still some more work that needs to be done. I've created a POC branch with this hack [here](https://github.com/jborean93/pypsrp/blob/client-imp/pypsrp/client.py#L161-L165). Still trying to see if there are any more performance improvements I can tweak out of it.

**Comment by jborean93** [comment]
Very similar to the existing copy function, maybe slightly slower, i.e. 15 seconds slower for a 1GB file which is an acceptable trade off for using the PSRP protocol instead of the raw transport.

**Comment by jborean93** [comment]
Thanks @nbulischeck for bringing this up and pushing through it, I've opened https://github.com/jborean93/pypsrp/pull/51 which changes copy to use PSRP instead of raw WSMan. If you have time it would be great if you could test it out. I've checked it against PowerShell versions 2 to 7-preview.3 so I'm fairly confident the "hack" works.
